/*
 * UIFont+NTNamedFonts.m
 *
 */


#import <objc/runtime.h>

#import <CoreText/CoreText.h>


@implementation UIFont (NTNamedFonts)


#pragma mark - Helper methods


+(NSString *)selectorNameForFontName:(NSString *)fontName
{
    fontName = [fontName stringByReplacingOccurrencesOfString:@"-" withString:@""];
    
    return [NSString stringWithFormat:@"%c%@OfSize:", tolower([fontName characterAtIndex:0]), [fontName substringFromIndex:1]];
}


+(NSString *)fontNameForSelectorName:(NSString *)selectorName
{
    // We need to create a lookup table to do this...
    
    static NSDictionary *selectorNamesToFontNames;
    
    static dispatch_once_t onceToken;
    
    dispatch_once(&onceToken, ^
    {
        NSMutableDictionary *d = [NSMutableDictionary dictionary];
        
        for(NSString *familyName in [UIFont familyNames])
        {
            for(NSString *fontName in [UIFont fontNamesForFamilyName:familyName])
            {
                d[[self selectorNameForFontName:fontName]] = fontName;
            }
        }
        
        selectorNamesToFontNames = [d copy];
    });

    return selectorNamesToFontNames[selectorName];
}


#pragma mark - Dynamic method support


static id createNamedFontIMP(Class class, SEL _cmd, CGFloat size)
{
    NSString *selectorName = NSStringFromSelector(_cmd);
    NSString *fontName = [class fontNameForSelectorName:selectorName];
    
    return [class fontWithName:fontName size:size];
}


+(BOOL)resolveClassMethod:(SEL)sel
{
    NSString *selectorName = NSStringFromSelector(sel);
    NSString *fontName = [self fontNameForSelectorName:selectorName];
    
    if ( !fontName )
        return [super resolveClassMethod:sel];
    
    Class metaClass = object_getClass(self);

    class_addMethod(metaClass, sel, (IMP)createNamedFontIMP, "@#:f");

    return YES;
}


#pragma mark - Code Generator to aid in creating UIFont+CustomFonts.h/m


#ifdef DEBUG


+(NSDictionary *)builtinFontVersions    // Generated by NTNamedFontsBootstrap
{
    static NSDictionary *builtinFontVersions = nil;
    
    static dispatch_once_t onceToken;
    
    dispatch_once(&onceToken, ^
                  {
                      builtinFontVersions =
                      @{
                        @"AcademyEngravedLetPlain": @"6.0",
                        @"AlNile": @"7.0",
                        @"AlNile-Bold": @"7.0",
                        @"AmericanTypewriter": @"6.0",
                        @"AmericanTypewriter-Bold": @"6.0",
                        @"AmericanTypewriter-Condensed": @"6.0",
                        @"AmericanTypewriter-CondensedBold": @"6.0",
                        @"AmericanTypewriter-CondensedLight": @"6.0",
                        @"AmericanTypewriter-Light": @"6.0",
                        @"AppleColorEmoji": @"6.0",
                        @"AppleSDGothicNeo-Bold": @"6.0",
                        @"AppleSDGothicNeo-Light": @"7.0",
                        @"AppleSDGothicNeo-Medium": @"6.0",
                        @"AppleSDGothicNeo-Regular": @"7.0",
                        @"AppleSDGothicNeo-SemiBold": @"7.0",
                        @"AppleSDGothicNeo-Thin": @"7.0",
                        @"Arial-BoldItalicMT": @"6.0",
                        @"Arial-BoldMT": @"6.0",
                        @"Arial-ItalicMT": @"6.0",
                        @"ArialHebrew": @"6.0",
                        @"ArialHebrew-Bold": @"6.0",
                        @"ArialHebrew-Light": @"7.0",
                        @"ArialMT": @"6.0",
                        @"ArialRoundedMTBold": @"6.0",
                        @"Avenir-Black": @"6.0",
                        @"Avenir-BlackOblique": @"6.0",
                        @"Avenir-Book": @"6.0",
                        @"Avenir-BookOblique": @"6.0",
                        @"Avenir-Heavy": @"6.0",
                        @"Avenir-HeavyOblique": @"6.0",
                        @"Avenir-Light": @"6.0",
                        @"Avenir-LightOblique": @"6.0",
                        @"Avenir-Medium": @"6.0",
                        @"Avenir-MediumOblique": @"6.0",
                        @"Avenir-Oblique": @"6.0",
                        @"Avenir-Roman": @"6.0",
                        @"AvenirNext-Bold": @"6.0",
                        @"AvenirNext-BoldItalic": @"6.0",
                        @"AvenirNext-DemiBold": @"6.0",
                        @"AvenirNext-DemiBoldItalic": @"6.0",
                        @"AvenirNext-Heavy": @"6.0",
                        @"AvenirNext-HeavyItalic": @"6.0",
                        @"AvenirNext-Italic": @"6.0",
                        @"AvenirNext-Medium": @"6.0",
                        @"AvenirNext-MediumItalic": @"6.0",
                        @"AvenirNext-Regular": @"6.0",
                        @"AvenirNext-UltraLight": @"6.0",
                        @"AvenirNext-UltraLightItalic": @"6.0",
                        @"AvenirNextCondensed-Bold": @"6.0",
                        @"AvenirNextCondensed-BoldItalic": @"6.0",
                        @"AvenirNextCondensed-DemiBold": @"6.0",
                        @"AvenirNextCondensed-DemiBoldItalic": @"6.0",
                        @"AvenirNextCondensed-Heavy": @"6.0",
                        @"AvenirNextCondensed-HeavyItalic": @"6.0",
                        @"AvenirNextCondensed-Italic": @"6.0",
                        @"AvenirNextCondensed-Medium": @"6.0",
                        @"AvenirNextCondensed-MediumItalic": @"6.0",
                        @"AvenirNextCondensed-Regular": @"6.0",
                        @"AvenirNextCondensed-UltraLight": @"6.0",
                        @"AvenirNextCondensed-UltraLightItalic": @"6.0",
                        @"BanglaSangamMN": @"6.0",
                        @"BanglaSangamMN-Bold": @"6.0",
                        @"Baskerville": @"6.0",
                        @"Baskerville-Bold": @"6.0",
                        @"Baskerville-BoldItalic": @"6.0",
                        @"Baskerville-Italic": @"6.0",
                        @"Baskerville-SemiBold": @"6.0",
                        @"Baskerville-SemiBoldItalic": @"6.0",
                        @"BodoniOrnamentsITCTT": @"6.0",
                        @"BodoniSvtyTwoITCTT-Bold": @"6.0",
                        @"BodoniSvtyTwoITCTT-Book": @"6.0",
                        @"BodoniSvtyTwoITCTT-BookIta": @"6.0",
                        @"BodoniSvtyTwoOSITCTT-Bold": @"6.0",
                        @"BodoniSvtyTwoOSITCTT-Book": @"6.0",
                        @"BodoniSvtyTwoOSITCTT-BookIt": @"6.0",
                        @"BodoniSvtyTwoSCITCTT-Book": @"6.0",
                        @"BradleyHandITCTT-Bold": @"6.0",
                        @"ChalkboardSE-Bold": @"6.0",
                        @"ChalkboardSE-Light": @"6.0",
                        @"ChalkboardSE-Regular": @"6.0",
                        @"Chalkduster": @"6.0",
                        @"Cochin": @"6.0",
                        @"Cochin-Bold": @"6.0",
                        @"Cochin-BoldItalic": @"6.0",
                        @"Cochin-Italic": @"6.0",
                        @"Copperplate": @"6.0",
                        @"Copperplate-Bold": @"6.0",
                        @"Copperplate-Light": @"6.0",
                        @"Courier": @"6.0",
                        @"Courier-Bold": @"6.0",
                        @"Courier-BoldOblique": @"6.0",
                        @"Courier-Oblique": @"6.0",
                        @"CourierNewPS-BoldItalicMT": @"6.0",
                        @"CourierNewPS-BoldMT": @"6.0",
                        @"CourierNewPS-ItalicMT": @"6.0",
                        @"CourierNewPSMT": @"6.0",
                        @"DINAlternate-Bold": @"7.0",
                        @"DINCondensed-Bold": @"7.0",
                        @"Damascus": @"7.0",
                        @"DamascusBold": @"7.0",
                        @"DamascusMedium": @"7.0",
                        @"DamascusSemiBold": @"7.0",
                        @"DevanagariSangamMN": @"6.0",
                        @"DevanagariSangamMN-Bold": @"6.0",
                        @"Didot": @"6.0",
                        @"Didot-Bold": @"6.0",
                        @"Didot-Italic": @"6.0",
                        @"DiwanMishafi": @"7.0",
                        @"EuphemiaUCAS": @"6.0",
                        @"EuphemiaUCAS-Bold": @"6.0",
                        @"EuphemiaUCAS-Italic": @"6.0",
                        @"Farah": @"7.0",
                        @"Futura-CondensedExtraBold": @"6.0",
                        @"Futura-CondensedMedium": @"6.0",
                        @"Futura-Medium": @"6.0",
                        @"Futura-MediumItalic": @"6.0",
                        @"GeezaPro": @"6.0",
                        @"GeezaPro-Bold": @"6.0",
                        @"GeezaPro-Light": @"7.0",
                        @"Georgia": @"6.0",
                        @"Georgia-Bold": @"6.0",
                        @"Georgia-BoldItalic": @"6.0",
                        @"Georgia-Italic": @"6.0",
                        @"GillSans": @"6.0",
                        @"GillSans-Bold": @"6.0",
                        @"GillSans-BoldItalic": @"6.0",
                        @"GillSans-Italic": @"6.0",
                        @"GillSans-Light": @"6.0",
                        @"GillSans-LightItalic": @"6.0",
                        @"GujaratiSangamMN": @"6.0",
                        @"GujaratiSangamMN-Bold": @"6.0",
                        @"GurmukhiMN": @"6.0",
                        @"GurmukhiMN-Bold": @"6.0",
                        @"Helvetica": @"6.0",
                        @"Helvetica-Bold": @"6.0",
                        @"Helvetica-BoldOblique": @"6.0",
                        @"Helvetica-Light": @"6.0",
                        @"Helvetica-LightOblique": @"6.0",
                        @"Helvetica-Oblique": @"6.0",
                        @"HelveticaNeue": @"6.0",
                        @"HelveticaNeue-Bold": @"6.0",
                        @"HelveticaNeue-BoldItalic": @"6.0",
                        @"HelveticaNeue-CondensedBlack": @"6.0",
                        @"HelveticaNeue-CondensedBold": @"6.0",
                        @"HelveticaNeue-Italic": @"6.0",
                        @"HelveticaNeue-Light": @"6.0",
                        @"HelveticaNeue-LightItalic": @"6.0",
                        @"HelveticaNeue-Medium": @"6.0",
                        @"HelveticaNeue-MediumItalic": @"7.0",
                        @"HelveticaNeue-Thin": @"7.0",
                        @"HelveticaNeue-ThinItalic": @"7.0",
                        @"HelveticaNeue-UltraLight": @"6.0",
                        @"HelveticaNeue-UltraLightItalic": @"6.0",
                        @"HiraKakuProN-W3": @"6.0",
                        @"HiraKakuProN-W6": @"6.0",
                        @"HiraMinProN-W3": @"6.0",
                        @"HiraMinProN-W6": @"6.0",
                        @"HoeflerText-Black": @"6.0",
                        @"HoeflerText-BlackItalic": @"6.0",
                        @"HoeflerText-Italic": @"6.0",
                        @"HoeflerText-Regular": @"6.0",
                        @"IowanOldStyle-Bold": @"7.0",
                        @"IowanOldStyle-BoldItalic": @"7.0",
                        @"IowanOldStyle-Italic": @"7.0",
                        @"IowanOldStyle-Roman": @"7.0",
                        @"Kailasa": @"6.0",
                        @"Kailasa-Bold": @"6.0",
                        @"KannadaSangamMN": @"6.0",
                        @"KannadaSangamMN-Bold": @"6.0",
                        @"MalayalamSangamMN": @"6.0",
                        @"MalayalamSangamMN-Bold": @"6.0",
                        @"Marion-Bold": @"6.0",
                        @"Marion-Italic": @"6.0",
                        @"Marion-Regular": @"6.0",
                        @"MarkerFelt-Thin": @"6.0",
                        @"MarkerFelt-Wide": @"6.0",
                        @"Menlo-Bold": @"7.0",
                        @"Menlo-BoldItalic": @"7.0",
                        @"Menlo-Italic": @"7.0",
                        @"Menlo-Regular": @"7.0",
                        @"Noteworthy-Bold": @"6.0",
                        @"Noteworthy-Light": @"6.0",
                        @"Optima-Bold": @"6.0",
                        @"Optima-BoldItalic": @"6.0",
                        @"Optima-ExtraBlack": @"6.0",
                        @"Optima-Italic": @"6.0",
                        @"Optima-Regular": @"6.0",
                        @"OriyaSangamMN": @"6.0",
                        @"OriyaSangamMN-Bold": @"6.0",
                        @"Palatino-Bold": @"6.0",
                        @"Palatino-BoldItalic": @"6.0",
                        @"Palatino-Italic": @"6.0",
                        @"Palatino-Roman": @"6.0",
                        @"Papyrus": @"6.0",
                        @"Papyrus-Condensed": @"6.0",
                        @"PartyLetPlain": @"6.0",
                        @"STHeitiSC-Light": @"6.0",
                        @"STHeitiSC-Medium": @"6.0",
                        @"STHeitiTC-Light": @"6.0",
                        @"STHeitiTC-Medium": @"6.0",
                        @"SavoyeLetPlain": @"7.0",
                        @"SinhalaSangamMN": @"6.0",
                        @"SinhalaSangamMN-Bold": @"6.0",
                        @"SnellRoundhand": @"6.0",
                        @"SnellRoundhand-Black": @"6.0",
                        @"SnellRoundhand-Bold": @"6.0",
                        @"Superclarendon-Black": @"7.0",
                        @"Superclarendon-BlackItalic": @"7.0",
                        @"Superclarendon-Bold": @"7.0",
                        @"Superclarendon-BoldItalic": @"7.0",
                        @"Superclarendon-Italic": @"7.0",
                        @"Superclarendon-Light": @"7.0",
                        @"Superclarendon-LightItalic": @"7.0",
                        @"Superclarendon-Regular": @"7.0",
                        @"Symbol": @"6.0",
                        @"TamilSangamMN": @"6.0",
                        @"TamilSangamMN-Bold": @"6.0",
                        @"TeluguSangamMN": @"6.0",
                        @"TeluguSangamMN-Bold": @"6.0",
                        @"Thonburi": @"6.0",
                        @"Thonburi-Bold": @"6.0",
                        @"Thonburi-Light": @"7.0",
                        @"TimesNewRomanPS-BoldItalicMT": @"6.0",
                        @"TimesNewRomanPS-BoldMT": @"6.0",
                        @"TimesNewRomanPS-ItalicMT": @"6.0",
                        @"TimesNewRomanPSMT": @"6.0",
                        @"Trebuchet-BoldItalic": @"6.0",
                        @"TrebuchetMS": @"6.0",
                        @"TrebuchetMS-Bold": @"6.0",
                        @"TrebuchetMS-Italic": @"6.0",
                        @"Verdana": @"6.0",
                        @"Verdana-Bold": @"6.0",
                        @"Verdana-BoldItalic": @"6.0",
                        @"Verdana-Italic": @"6.0",
                        @"ZapfDingbatsITC": @"6.0",
                        @"Zapfino": @"6.0",
                        };
                  });
    
    return builtinFontVersions;
}


+(NSMutableSet *)actualSelectorNamesWithMessages:(NSMutableArray *)messages
{
    unsigned int numMethods;
    Method *methods = class_copyMethodList(object_getClass([UIFont class]), &numMethods);
    
    NSMutableSet *exisitingSelectorNames = [NSMutableSet set];
    
    for(int index=0; index<numMethods; index++)
    {
        Method method = methods[index];
        
        SEL sel = method_getName(method);
        
        NSString *selectorName = NSStringFromSelector(sel);
        
        if ( ![selectorName hasSuffix:@"OfSize:"] || [selectorName hasPrefix:@"_"] || [selectorName hasSuffix:@"FontOfSize:"] )
            continue ;
        
        [exisitingSelectorNames addObject:selectorName];
    }
    
    free(methods);
    
    return exisitingSelectorNames;
}


+(NSSet *)expectedSelectorNamesWithMessages:(NSMutableArray *)messages
{
    NSMutableSet *expectedSelectorNames = [NSMutableSet set];
    
    NSArray *filenames = [[NSBundle mainBundle].infoDictionary objectForKey:@"UIAppFonts"];
    
    if ( !filenames )
        return [expectedSelectorNames copy];
    
    for(NSString *filename in filenames)
    {
        NSURL *fileUrl = [[NSBundle mainBundle] URLForResource:[filename stringByDeletingPathExtension] withExtension:[filename pathExtension]];
        
        if ( !fileUrl )
        {
            [messages addObject:[NSString stringWithFormat:@"Warning: Font file %@ is defined in info.plist, but is not loadable", filename]];
            continue;
        }
        
        NSArray *fontDescriptors = (__bridge_transfer NSArray *)CTFontManagerCreateFontDescriptorsFromURL((__bridge CFURLRef)fileUrl);
        
        if ( !fontDescriptors )
        {
            [messages addObject:[NSString stringWithFormat:@"Warning: Font file %@ is defined in info.plist, but no font descriptors were found", filename]];
            return nil;
        }
        
        for (NSDictionary *fontDescriptor in fontDescriptors)
        {
            NSString *fontName = [fontDescriptor objectForKey:@"NSFontNameAttribute"];
            
            if (!fontName)
            {
                [messages addObject:[NSString stringWithFormat:@"Warning: Font file %@ has an invalid font descriptor (name not found)", filename]];
                continue;
            }
            
            [expectedSelectorNames addObject:[self selectorNameForFontName:fontName]];
        }
    }
    
    return [expectedSelectorNames copy];
}


+(BOOL)detectCustomFontsShowingAlert:(BOOL)showAlert
{
    // Checks for any new custom fonts, if found will output the new UIFont+CustomFonts.h file
    // and optionally display an UIAlertView
    // Does nothing in non-DEBUG builds
    
    NSMutableArray *messages = [NSMutableArray array];
    NSSet *expectedSelectorNames = [self expectedSelectorNamesWithMessages:messages];
    NSSet *actualSelectorNames = [self actualSelectorNamesWithMessages:messages];
    
    if ( [expectedSelectorNames isEqualToSet:actualSelectorNames] && !messages.count )
        return YES;  // all looks good.
    
    NSMutableSet *addedSelectorNames = [expectedSelectorNames mutableCopy];
    [addedSelectorNames minusSet:actualSelectorNames];
    
    NSMutableSet *removedSelectorNames = [actualSelectorNames mutableCopy];
    [removedSelectorNames minusSet:expectedSelectorNames];

    if ( addedSelectorNames.count || removedSelectorNames.count )
    {
        NSMutableString *h = [NSMutableString string];
        NSMutableString *m = [NSMutableString string];
        
        [h appendString:
         @"/*\n"
         @" * UIFont+CustomFonts.h\n"
         @" *\n"
         @" * Generated by NTNamedFonts - https://github.com/NagelTech/NTNamedFonts\n"
         @" */\n"
         @"\n"
         @"\n"
         @"@interface UIFont (CustomFonts)\n"];
        
        [m appendString:
         @"/*\n"
         @" * UIFont+CustomFonts.m\n"
         @" *\n"
         @" * Generated by NTNamedFonts - https://github.com/NagelTech/NTNamedFonts\n"
         @" */\n"
         @"\n"
         @"\n"
         @"@implementation UIFont (CustomFonts)\n"
         @"\n\n"];
        
        for(NSString *familyName in [[UIFont familyNames] sortedArrayUsingSelector:@selector(compare:)])
        {
            BOOL outputFamilyName = YES;
            
            for(NSString *fontName in [[UIFont fontNamesForFamilyName:familyName] sortedArrayUsingSelector:@selector(compare:)])
            {
                NSString *selectorName = [self selectorNameForFontName:fontName];
                
                if ( ![expectedSelectorNames containsObject:selectorName] )
                    continue;    // we are only looking at custom fonts, ignore all others
                
                if ( outputFamilyName )
                {
                    outputFamilyName = NO;
                    
                    [h appendFormat:@"\n// %@\n\n", familyName];
                    [m appendFormat:@"#pragma mark %@\n\n\n", familyName];
                }
                
                [h appendFormat:@"+(UIFont *)%@(CGFloat)size;\n", selectorName];
                [m appendFormat:
                 @"+(UIFont *)%@(CGFloat)size\n"
                 @"{\n"
                 @"    return [UIFont fontWithName:@\"%@\" size:size];\n"
                 @"}\n"
                 @"\n\n", selectorName, fontName];
            }
        }
        
        [h appendString:@"\n@end\n"];
        [m appendString:@"@end\n"];
        
        [messages addObject:@"Custom font changes detected!"];
        
        if ( addedSelectorNames.count )
        {
            [messages addObject:[NSString stringWithFormat:@"Added: %@", [addedSelectorNames.allObjects componentsJoinedByString:@", "]]];
        }
        
        if ( removedSelectorNames.count )
        {
            [messages addObject:[NSString stringWithFormat:@"Removed: %@", [removedSelectorNames.allObjects componentsJoinedByString:@", "]]];
        }
        
        [messages addObject:@"New m/h files have been generated to your log."];
        
        NSLog(@"%@", [messages componentsJoinedByString:@"\n"]);
        NSLog(@"* * * * * * * * * * * * * * * * * * *");
        NSLog(@"\n%@\n", h);
        NSLog(@"* * * * * * * * * * * * * * * * * * *");
        NSLog(@"\n%@\n", m);
        NSLog(@"* * * * * * * * * * * * * * * * * * *");
    }
    else
        NSLog(@"%@", [messages componentsJoinedByString:@"\n"]);
    
    if ( showAlert )
    {
        UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"CustomFont changes detected"
                                                            message:[messages componentsJoinedByString:@"\n"]
                                                           delegate:nil
                                                  cancelButtonTitle:@"Ok"
                                                  otherButtonTitles:nil];
        [alertView show];
    }
    
    return YES;
}


#else


+(BOOL)detectCustomFontsShowingAlert:(BOOL)showAlert
{
    return NO;
}


#endif


@end

