/*
 * UIFont+CustomFonts.h
 *
 * Generated by NTNamedFonts - https://github.com/NagelTech/NTNamedFonts
 */


@interface UIFont (CustomFonts)

// Kaushan Script

+(UIFont *)kaushanScriptRegularOfSize:(CGFloat)size;

// Roboto

+(UIFont *)robotoBoldOfSize:(CGFloat)size;
+(UIFont *)robotoItalicOfSize:(CGFloat)size;
+(UIFont *)robotoRegularOfSize:(CGFloat)size;

@end
