/*
 * UIFont+CustomFonts.m
 *
 * Generated by NTNamedFonts - https://github.com/NagelTech/NTNamedFonts
 */


@implementation UIFont (CustomFonts)


#pragma mark Kaushan Script


+(UIFont *)kaushanScriptRegularOfSize:(CGFloat)size
{
    return [UIFont fontWithName:@"KaushanScript-Regular" size:size];
}


#pragma mark Roboto


+(UIFont *)robotoBoldOfSize:(CGFloat)size
{
    return [UIFont fontWithName:@"Roboto-Bold" size:size];
}


+(UIFont *)robotoItalicOfSize:(CGFloat)size
{
    return [UIFont fontWithName:@"Roboto-Italic" size:size];
}


+(UIFont *)robotoRegularOfSize:(CGFloat)size
{
    return [UIFont fontWithName:@"Roboto-Regular" size:size];
}


@end